#!/usr/bin/env bash
# Generate public_html/assets/config.js from .env at project root.
# Run before deploying: ./scripts/build-config.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT_FILE="$ROOT/public_html/assets/config.js"

if [ ! -f "$ENV_FILE" ]; then
  echo "Error: .env not found at $ENV_FILE" >&2
  echo "Copy .env.example to .env and fill in values." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

if [ -z "${APPS_SCRIPT_URL:-}" ]; then
  echo "Error: APPS_SCRIPT_URL is not set in .env" >&2
  exit 1
fi

# Escape backslashes and double-quotes for safe JS string embedding.
escaped=$(printf '%s' "$APPS_SCRIPT_URL" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')

cat > "$OUT_FILE" <<EOF
// Auto-generated by scripts/build-config.sh — do not edit by hand.
// Source of truth: .env at project root.
window.USE_CONFIG = {
  endpoint: "$escaped"
};
EOF

echo "Wrote $OUT_FILE (endpoint: $APPS_SCRIPT_URL)"
