#!/usr/bin/env bash
# Generate public_html/api/secrets.php from .env at the project root.
# Run before deploying: ./scripts/build-secrets.sh
# secrets.php is gitignored — upload it alongside the rest of public_html/.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT_FILE="$ROOT/public_html/api/secrets.php"

if [ ! -f "$ENV_FILE" ]; then
  echo "Error: .env not found at $ENV_FILE" >&2
  echo "Copy .env.example to .env and fill in values." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

require_var() {
  local name="$1"
  local val
  val="$(eval "printf %s \"\${$name:-}\"")"
  if [ -z "$val" ]; then
    echo "Error: $name is not set in .env" >&2
    exit 1
  fi
}

require_var DB_HOST
require_var DB_NAME
require_var DB_USER
require_var APPS_SCRIPT_URL
require_var ADMIN_TOKEN

# Escape backslashes and single quotes for safe single-quoted PHP strings.
php_quote() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e "s/'/\\\\'/g"
}

DB_PASS_VAL="${DB_PASS:-}"

cat > "$OUT_FILE" <<EOF
<?php
// Auto-generated by scripts/build-secrets.sh — do not edit by hand.
// Source of truth: .env at the project root.

return [
  'db_host'         => '$(php_quote "$DB_HOST")',
  'db_name'         => '$(php_quote "$DB_NAME")',
  'db_user'         => '$(php_quote "$DB_USER")',
  'db_pass'         => '$(php_quote "$DB_PASS_VAL")',
  'apps_script_url' => '$(php_quote "$APPS_SCRIPT_URL")',
  'admin_token'     => '$(php_quote "$ADMIN_TOKEN")',
];
EOF

chmod 600 "$OUT_FILE"
echo "Wrote $OUT_FILE"
